### ISSUE TITLE
Command-line 'Extract Network' fails to recognize output

### ISSUE THREAD

**Issue by mrbende** [SystemsGenetics/KINC#58]
The qkinc GUI for Extract Network did not allow me to input a minimum correlation value, similar to issue #56. I tried to run the following command-line argument instead, and received the following error: 

```
[mrbende@node0098 EDS1014]$ kinc run extract --emx EDS1014.emx --ccm EDS1014.cmx --output EDS1014_network95.txt --mincorr 0.95
--------------------------------------------------------------------------
The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca mpi_cuda_support 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
--------------------------------------------------------------------------
../../src/console/ace_run.cpp:315
void Ace::Run::addArguments()
INVALID OPTION
Unknown analytic option 'output'.
```

I have the following modules added:

```
[mrbende@node0098 EDS1014]$ ls
EDS1014.ccm  EDS1014.cmx  EDS1014.emx  EDS1014_GEM.txt  EDS1014_network95.txt
[mrbende@node0098 EDS1014]$ module list
Currently Loaded Modulefiles:
  1) use.own                3) gcc/5.4.0              5) openmpi/1.10.7         7) ACE/develop            9) KINC/develop
  2) cuda-toolkit/9.0.176   4) openmpi/1.10.7-eth     6) Qt/5.9.2               8) gsl/2.3
```
This is potentially the error behind the GUI failure in issue #56.

**Comment by spficklin** [comment]
I think the CUDA error is something on the Palmetto side. Are you sure you've loaded the right CUDA library module?  

The issue with not being able to enter the min correlation value in the GUI has been fixed in the devel branch by @4ctrl-alt-del .  You can pull ACE and recompile it.  Then KINC should pick up the new shared library and let you edit the field in the GUI.

**Comment by mrbende** [comment]
I have updated to the newest updates of both ACE and KINC in palmetto. I still receive the same error. I run the following command in my script to run rmt to achieve a threshold value:
```
# determine threshold value
kinc run rmt --input EDS1014.cmx --log EDS1014.log

# read threshold from log file
THRESHOLD=$(tail -n 1 EDS1014.log)

# extract network file from threshold similarity matrix
kinc run extract --emx EDS1014.emx --ccm EDS1014.cmx --output EDS1014-net.txt --mincorr $THRESHOLD
```

I have the use.own module created by @bentsherman loaded, and KINC is loaded as a module. 

This is the error I still receive in the output file:
```
../../src/console/ace_run.cpp:315
void Ace::Run::addArguments()
INVALID OPTION
Unknown analytic option 'output'.
```

**Comment by bentsherman** [comment]
Reed, I updated your comments to make those code blocks look like code blocks, you can "edit" the comment to see what the syntax looks like. If you could use that in the future that would be helpful.

I'm guessing that your KINC build is out of date. To be sure that it gets updated, just remove it from your home directory:
```
cd ~
rm -rf ACE KINC
```

My install scripts use those directories as a "cache" so if you delete them then my script will re-clone them with the latest commits.

**Comment by mrbende** [comment]
Thank you for the note on formatting, I'll be sure to stick to that in the future. I will try re-cloning using your script rather than manually.
